name: Test and lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: blog
          POSTGRES_DB: blog
          POSTGRES_PASSWORD: blog
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Load schema to test database
        env:
          RAILS_ENV: test
          SESSION_SCOPE: ""
          DB_NAME: ""
          DB_USERNAME: blog
          DB_PASSWORD: blog
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          SESSION_SCOPE: ""
          DB_NAME: ""
          DB_USERNAME: blog
          DB_PASSWORD: blog
        run: |
          bin/rails db:test:prepare
          bin/rails test

      - name: Run lint
        run: |
          gem install rubocop
          rubocop
